export const USER_UPDATE_START = 'USER_UPDATE_START';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
export const CLEAR_MOVIES = 'CLEAR_MOVIES';

export const GET_MOVIES_START = 'GET_MOVIES_START';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIES_FAIL = 'GET_MOVIES_FAIL';

export const POST_MOVIE_START = 'POST_MOVIE_START';
export const POST_MOVIE_SUCCESS = 'POST_MOVIE_SUCCESS';
export const POST_MOVIE_FAIL = 'POST_MOVIE_FAIL';

export const SHOW_MOVIE_SUCCESS = 'SHOW_MOVIE_SUCCESS';
export const SHOW_MOVIE_FAIL = 'SHOW_MOVIE_FAIL';

export const GET_OMDB_SUCCESS = 'GET_OMDB_SUCCESS';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
