# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 998393a8e17aec62a932f538bc8cb2cb1f47db5505b1c4dba7eaf02136b964873c90df9a7a47bf705bf00a106a0bf29a54ae40478bd311f8e954e4fe442607d6

test:
  secret_key_base: 574b4437d8696aed5728bd056799a920be3fa557b0faaa76e5c8c25fb73f218a6859fbc19babdb7483c33ed187c2c85c068ff872bc84e879900b169770b08992

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
