# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f98f9664ca1d0e8974e2373bfcf5df44ff55e785c967b3f8ce47233a2511cd071fce58409946246ed4f60f3b027834395cfbf2cc50b6d879442df7523f47c739

test:
  secret_key_base: c345d714a5fe559049a571b8af38dd6f53bba45c059665c841bb7683e683a98f8a07e5d2aebf26b69f024b93d313d5664abbaf9c155205aac149f2c5666e1d21

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
